import sys
from pathlib import Path
if sys.platform == "win32":
    DRIVE_ROOT = Path("C:/")
else:
    DRIVE_ROOT = Path("/mnt/c/")
LOG_FILE_PATH = ''
ROOT_DATA_PATH = DRIVE_ROOT / Path("")
SPECIES_LIST = ''
MIN_CONFIDENCE = 0.3
OVERLAP = 0
GAP_MS = 100
EXTERNAL_DRIVE = 'D'
# HDBSCAN
MIN_CLUSTER_SIZE = 10 # 4 baseline
MIN_SAMPLES = 5 # 3 baseline
CLUSTER_METRIC = 'euclidean'
CLUSTER_SELECTION_EPSILON = 0
# UMAP Cluster
N_NEIGHBORS = 15
MIN_DISTANCE = 0.0
N_COMPONENTS = 8
NMAP_METRIC = 'cosine'
RANDOM_STATE = 42
# UMAP Vizualization
N_NEIGHBORS_VIZ = 15
MIN_DISTANCE_VIZ = 0.0
N_COMPONENTS_VIZ = 2
NMAP_METRIC_VIZ = 'cosine'
RANDOM_STATE_VIZ = 42
ANALYSIS_RUN_TEXT = ''
ANALYZE_FILE_GROUP = ''
SQLSERVER_NAME = 'AWW_AUTOMATE\\SQLEXPRESS'
SQLSERVER_DATABASE = 'BirdGuide'
SQLSERVER_USERNAME = 'python'
SQLSERVER_TOKEN = ''
SQLSERVER_KEY = ''
