ROOT_DATA_PATH = ""
SPECIES_LIST = 'philippines.txt'
MIN_CONFIDENCE = 0.7
GAP_MS = 100
EXTERNAL_DRIVE = 'D'
# HDBSCAN
MIN_CLUSTER_SIZE = 10 # 4 baseline
MIN_SAMPLES = 7 # 3 baseline
CLUSTER_METRIC = 'euclidean'
CLUSTER_SELECTION_EPSILON = .1
# UMAP
N_NEIGHBORS = 15
MIN_DISTANCE = 0.0
N_COMPONENTS = 8
NMAP_METRIC = 'cosine'
RANDOM_STATE = 42
# UMAP
N_NEIGHBORS_SEC = 15
MIN_DISTANCE_SEC = 0.0
N_COMPONENTS_SEC = 2
NMAP_METRIC_SEC = 'cosine'
RANDOM_STATE_SEC = 42
ANALYSIS_RUN_TEXT = 'rev_clu_sam'
ANALYZE_FILE_GROUP = 'aw_chipbot_01_2026-08-07_09_15_27_39.875337_-86.284028'